### ISSUE TITLE
Error on module import

### ISSUE THREAD

**Issue by adanielyan** [timbur/react-mixin-decorator#1]
I'm getting the following error when trying to import the react-mixin-decorator:

```SyntaxError: 'import' and 'export' may appear only with 'sourceType: module```

Please advise.

**Comment by timbur** [comment]
I googled your error message and would I be correct in saying you're using `browserify` and/or `babelify`?  I wrote this module using ES6, so you'll need to use a transpiler like `babel` during your build-step.  It's easier to create the HOC using ES6, but I can always distribute a ES5 version if that would make it easier for you to use this.

**Comment by adanielyan** [comment]
Thank you for responding. In fact I do use browserify and babelify. I have other modules written in es6 that compile without a problem.

**Comment by timbur** [comment]
Alright try updating to v1.1.3.  I added a prepublish build step.

**Comment by elverskog** [comment]
I had the same problem and with the new version it works. I had previously pulled the code out of the module into my components dir just to give it a test run (which is crazy but it worked). Thanks for the quick fix.

**Comment by timbur** [comment]
Cool, thanks for the feedback.  I'll make sure to include a prepublish build step for all my ES6 packages from here on.  :)
