### ISSUE TITLE
v2.0.0 suggestions?

### ISSUE THREAD

**Issue by timbur** [timbur/react-mixin-decorator#3]
ES6 and React were pretty new to me when I made this, and it's become apparent that some things could be changed to make it easier to convert the more complex mixins to decorators, so I'll see about making some improvements when I get a chance.

In the mean time, does anyone have any suggestions or requests or use-cases I should look into?

**Comment by AshCoolman** [comment]
As Babel 6 has removed decorators, I tried this package with this (temporary) Babel-5-style-decorator Polyfill.

https://www.npmjs.com/package/babel-plugin-transform-decorators-legacy

I couldn't get it to work, but there are some differences from the original implementation:

> One important limitation, which is noted in the README, is that the decorators on class properties can only mutate the initializer itself, not enumerable, writable, and configurable, which is not in line with Babel 5's behavior, but is realistically probably not something that is used in the common usecases.
- loganfsmyth @ https://phabricator.babeljs.io/T2645

If this is indeed the problem, perhaps this could be a target? Reading [this](https://github.com/wycats/javascript-decorators/pull/36) makes me think official decorator support is a while off.

Ta

**Comment by timbur** [comment]
Will this package need to be updated to match the official decorator spec regardless of Babel?  Or is the issue specific to Babel 6?

**Comment by AshCoolman** [comment]
I can't speak with any authority on this at the moment - but I will research in a few hours.

I agree that the lifetime of this legacy package will greatly level of effort (if any)  that is warranted.

**Comment by AshCoolman** [comment]
Finally got around to doing some research!

**What decorator support does Babel 5 and Babel 6 have?**

>  ...the intention is still for Babel 6 to implement the new proposal once it has been officially presented to TC39.

-source: loganfsmyth on [Phabricator](https://phabricator.babeljs.io/T2645#anchor-67560)

So Babel 5 supported the old decorator spec, Babel 6 will support the new decorator spec - when the new spec is settled.

Which begs the question: 

**When will the new spec be settled and (supported by Babel 6)?**

> **Answer: ...when wycats feels the proposal is ready**

-source: logalfsmyth on Phabricator [question](https://phabricator.babeljs.io/T2645#anchor-69585)/[answer](https://phabricator.babeljs.io/T2645#anchor-69610)

**References**

* [Babel 5 style legacy decorator plugin](https://github.com/loganfsmyth/babel-plugin-transform-decorators-legacy)
* [Phabricator question](https://phabricator.babeljs.io/T2645#anchor-69585)
* [Babel: The Road to 1.0](https://github.com/jayphelps/core-decorators.js/issues/15)
* https://github.com/timbur/react-mixin-decorator/issues/3

**Comment by timbur** [comment]
Thanks for the info!  I guess this means I should probably hold off on v2 until the decorator spec is finalized eh?

**Comment by timbur** [comment]
Thanks for the info!  I guess this means I should probably hold off on v2 until the decorator spec is finalized eh?  Or do you think there is something that can be done to make this work with `babel-plugin-transform-decorators-legacy`?

**Comment by AshCoolman** [comment]
Yeah I think you are best waiting for v2, ultimately people can stick with Babel 5 (or use Typescript?).

Its a pity we have to wait on wycats for the spec but, thats life in ES7 land I guess.

I've not looked into `babel-plugin-transform-decorators-legacy`, so I have no idea. Though the comments in the Babel Phabricator make it seem like it wasn't the easiest thing to write
